title: micro:bit pauses
hero_image: images/banner.png
description: Using the pause block to add a delay
version: 4
listed: false
copyedit: false
last_tested: "2023-09-26"
steps:
  - title: Introduction
